version: '3'
services:
  hexo:
    container_name: hexo
    build:
      context: ./hexo
    # restart: always
    environment:
      HEXO_SERVER_PORT: 4000
      SITE_PORT: 4000
      GIT_USER: ${GIT_USER}
      GIT_EMAIL: ${GIT_EMAIL}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      TIME_ZONE: ${TIME_ZONE}
    ports:
      - ${SITE_PORT}:4000
    volumes:
      - ./app:/app
